steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'northamerica-northeast1-docker.pkg.dev/mineral-anchor-361313/gcp-tagging/tag-image:$COMMIT_SHA', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'northamerica-northeast1-docker.pkg.dev/mineral-anchor-361313/gcp-tagging/tag-image:$COMMIT_SHA']
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloud-run-tagging', '--image', 'northamerica-northeast1-docker.pkg.dev/mineral-anchor-361313/gcp-tagging/tag-image:$COMMIT_SHA', '--region', 'northamerica-northeast1']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'cloud-run-tagging'
  - '--image'
  - 'northamerica-northeast1-docker.pkg.dev/mineral-anchor-361313/gcp-tagging/tag-image:$COMMIT_SHA'
  - '--region'
  - 'northamerica-northeast1'
  - '--set-env-vars="FLASK_PORT=8080"'
  - '--set-env-vars="API_NAME=compute"'
  - '--set-env-vars="gs://gcp-tags"'
  - '-trigger-http'
  - '--no-allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
